# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pymaid/pb/pymaid.proto

import sys
_b = sys.version_info[0] < 3 and (
    lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name='pymaid/pb/pymaid.proto',
    package='pymaid.pb',
    syntax='proto3',
    serialized_pb=_b('\n\x16pymaid/pb/pymaid.proto\x12\tpymaid.pb\x1a\x19google/protobuf/any.proto\"\x8d\x02\n\nController\x12\x16\n\x0eservice_method\x18\x01 \x01(\t\x12\x35\n\x0bpacket_type\x18\x02 \x01(\x0e\x32 .pymaid.pb.Controller.PacketType\x12\x17\n\x0ftransmission_id\x18\x03 \x01(\r\x12\x13\n\x0bis_canceled\x18\x04 \x01(\x08\x12\x11\n\tis_failed\x18\x05 \x01(\x08\x12\'\n\textension\x18\x0f \x01(\x0b\x32\x14.google.protobuf.Any\"F\n\nPacketType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07REQUEST\x10\x01\x12\x0c\n\x08RESPONSE\x10\x02\x12\x10\n\x0cNOTIFICATION\x10\x03\"\x08\n\x06RpcAck\"\x06\n\x04Void\"-\n\x0c\x45rrorMessage\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\tb\x06proto3'),
    dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR, ])


_CONTROLLER_PACKETTYPE = _descriptor.EnumDescriptor(
    name='PacketType',
    full_name='pymaid.pb.Controller.PacketType',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='UNKNOWN', index=0, number=0,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='REQUEST', index=1, number=1,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='RESPONSE', index=2, number=2,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='NOTIFICATION', index=3, number=3,
            options=None,
            type=None),
    ],
    containing_type=None,
    options=None,
    serialized_start=264,
    serialized_end=334,
)
_sym_db.RegisterEnumDescriptor(_CONTROLLER_PACKETTYPE)


_CONTROLLER = _descriptor.Descriptor(
    name='Controller',
    full_name='pymaid.pb.Controller',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='service_method', full_name='pymaid.pb.Controller.service_method', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='packet_type', full_name='pymaid.pb.Controller.packet_type', index=1,
            number=2, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='transmission_id', full_name='pymaid.pb.Controller.transmission_id', index=2,
            number=3, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='is_canceled', full_name='pymaid.pb.Controller.is_canceled', index=3,
            number=4, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='is_failed', full_name='pymaid.pb.Controller.is_failed', index=4,
            number=5, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='extension', full_name='pymaid.pb.Controller.extension', index=5,
            number=15, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
        _CONTROLLER_PACKETTYPE,
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=65,
    serialized_end=334,
)


_RPCACK = _descriptor.Descriptor(
    name='RpcAck',
    full_name='pymaid.pb.RpcAck',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=336,
    serialized_end=344,
)


_VOID = _descriptor.Descriptor(
    name='Void',
    full_name='pymaid.pb.Void',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=346,
    serialized_end=352,
)


_ERRORMESSAGE = _descriptor.Descriptor(
    name='ErrorMessage',
    full_name='pymaid.pb.ErrorMessage',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='code', full_name='pymaid.pb.ErrorMessage.code', index=0,
            number=1, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='message', full_name='pymaid.pb.ErrorMessage.message', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=354,
    serialized_end=399,
)

_CONTROLLER.fields_by_name['packet_type'].enum_type = _CONTROLLER_PACKETTYPE
_CONTROLLER.fields_by_name['extension'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_CONTROLLER_PACKETTYPE.containing_type = _CONTROLLER
DESCRIPTOR.message_types_by_name['Controller'] = _CONTROLLER
DESCRIPTOR.message_types_by_name['RpcAck'] = _RPCACK
DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['ErrorMessage'] = _ERRORMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Controller = _reflection.GeneratedProtocolMessageType('Controller', (_message.Message,), dict(
    DESCRIPTOR=_CONTROLLER,
    __module__='pymaid.pb.pymaid_pb2'
    # @@protoc_insertion_point(class_scope:pymaid.pb.Controller)
))
_sym_db.RegisterMessage(Controller)

RpcAck = _reflection.GeneratedProtocolMessageType('RpcAck', (_message.Message,), dict(
    DESCRIPTOR=_RPCACK,
    __module__='pymaid.pb.pymaid_pb2'
    # @@protoc_insertion_point(class_scope:pymaid.pb.RpcAck)
))
_sym_db.RegisterMessage(RpcAck)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
    DESCRIPTOR=_VOID,
    __module__='pymaid.pb.pymaid_pb2'
    # @@protoc_insertion_point(class_scope:pymaid.pb.Void)
))
_sym_db.RegisterMessage(Void)

ErrorMessage = _reflection.GeneratedProtocolMessageType('ErrorMessage', (_message.Message,), dict(
    DESCRIPTOR=_ERRORMESSAGE,
    __module__='pymaid.pb.pymaid_pb2'
    # @@protoc_insertion_point(class_scope:pymaid.pb.ErrorMessage)
))
_sym_db.RegisterMessage(ErrorMessage)


# @@protoc_insertion_point(module_scope)
