# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pymaid/ext/monitor/monitor.proto

from pymaid.rpc import pymaid_pb2 as pymaid_dot_rpc_dot_pymaid__pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='pymaid/ext/monitor/monitor.proto',
    package='pymaid.ext.monitor',
    syntax='proto3',
    serialized_options=b'\220\001\001',
    serialized_pb=b'\n pymaid/ext/monitor/monitor.proto\x12\x12pymaid.ext.monitor\x1a\x17pymaid/rpc/pymaid.proto\"\x0f\n\rHeartbeatResp2X\n\x0eMonitorService\x12\x46\n\x0fNotifyHeartbeat\x12\x10.pymaid.rpc.Void\x1a!.pymaid.ext.monitor.HeartbeatRespB\x03\x90\x01\x01\x62\x06proto3',
    dependencies=[pymaid_dot_rpc_dot_pymaid__pb2.DESCRIPTOR, ])


_HEARTBEATRESP = _descriptor.Descriptor(
    name='HeartbeatResp',
    full_name='pymaid.ext.monitor.HeartbeatResp',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=81,
    serialized_end=96,
)

DESCRIPTOR.message_types_by_name['HeartbeatResp'] = _HEARTBEATRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeartbeatResp = _reflection.GeneratedProtocolMessageType('HeartbeatResp', (_message.Message,), {
    'DESCRIPTOR': _HEARTBEATRESP,
    '__module__': 'pymaid.ext.monitor.monitor_pb2'
    # @@protoc_insertion_point(class_scope:pymaid.ext.monitor.HeartbeatResp)
})
_sym_db.RegisterMessage(HeartbeatResp)


DESCRIPTOR._options = None

_MONITORSERVICE = _descriptor.ServiceDescriptor(
    name='MonitorService',
    full_name='pymaid.ext.monitor.MonitorService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=98,
    serialized_end=186,
    methods=[
        _descriptor.MethodDescriptor(
            name='NotifyHeartbeat',
            full_name='pymaid.ext.monitor.MonitorService.NotifyHeartbeat',
            index=0,
            containing_service=None,
            input_type=pymaid_dot_rpc_dot_pymaid__pb2._VOID,
            output_type=_HEARTBEATRESP,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_MONITORSERVICE)

DESCRIPTOR.services_by_name['MonitorService'] = _MONITORSERVICE

MonitorService = service_reflection.GeneratedServiceType('MonitorService', (_service.Service,), dict(
    DESCRIPTOR=_MONITORSERVICE,
    __module__='pymaid.ext.monitor.monitor_pb2'
))

MonitorService_Stub = service_reflection.GeneratedServiceStubType('MonitorService_Stub', (MonitorService,), dict(
    DESCRIPTOR=_MONITORSERVICE,
    __module__='pymaid.ext.monitor.monitor_pb2'
))


# @@protoc_insertion_point(module_scope)
