# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: examples/hello/hello.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='examples/hello/hello.proto',
  package='hello',
  serialized_pb=_b('\n\x1a\x65xamples/hello/hello.proto\x12\x05hello\"\x0e\n\x0cHelloRequest\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x02(\t2B\n\x0cHelloService\x12\x32\n\x05hello\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponseB\x03\x90\x01\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='hello.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=51,
)


_HELLORESPONSE = _descriptor.Descriptor(
  name='HelloResponse',
  full_name='hello.HelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='hello.HelloResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloResponse'] = _HELLORESPONSE

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'examples.hello.hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloResponse = _reflection.GeneratedProtocolMessageType('HelloResponse', (_message.Message,), dict(
  DESCRIPTOR = _HELLORESPONSE,
  __module__ = 'examples.hello.hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloResponse)
  ))
_sym_db.RegisterMessage(HelloResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\220\001\001'))

_HELLOSERVICE = _descriptor.ServiceDescriptor(
  name='HelloService',
  full_name='hello.HelloService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=87,
  serialized_end=153,
  methods=[
  _descriptor.MethodDescriptor(
    name='hello',
    full_name='hello.HelloService.hello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLORESPONSE,
    options=None,
  ),
])

HelloService = service_reflection.GeneratedServiceType('HelloService', (_service.Service,), dict(
  DESCRIPTOR = _HELLOSERVICE,
  __module__ = 'examples.hello.hello_pb2'
  ))

HelloService_Stub = service_reflection.GeneratedServiceStubType('HelloService_Stub', (HelloService,), dict(
  DESCRIPTOR = _HELLOSERVICE,
  __module__ = 'examples.hello.hello_pb2'
  ))


# @@protoc_insertion_point(module_scope)
