# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: examples/complicated/pb.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='examples/complicated/pb.proto',
    package='complicated',
    syntax='proto3',
    serialized_options=b'\220\001\001',
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x1d\x65xamples/complicated/pb.proto\x12\x0b\x63omplicated\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xe5\x01\n\x12\x43omplicatedMessage\x12%\n\x07message\x18\x01 \x01(\x0b\x32\x14.complicated.Message\x12\x11\n\x05uints\x18\x02 \x03(\rB\x02\x10\x01\x12?\n\x08messages\x18\x03 \x03(\x0b\x32-.complicated.ComplicatedMessage.MessagesEntry\x12\r\n\x05\x63ount\x18\x04 \x01(\r\x1a\x45\n\rMessagesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.complicated.Message:\x02\x38\x01\x32S\n\x07Service\x12H\n\x04Test\x12\x1f.complicated.ComplicatedMessage\x1a\x1f.complicated.ComplicatedMessageB\x03\x90\x01\x01\x62\x06proto3'
)


_MESSAGE = _descriptor.Descriptor(
    name='Message',
    full_name='complicated.Message',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='message', full_name='complicated.Message.message', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=46,
    serialized_end=72,
)


_COMPLICATEDMESSAGE_MESSAGESENTRY = _descriptor.Descriptor(
    name='MessagesEntry',
    full_name='complicated.ComplicatedMessage.MessagesEntry',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='key', full_name='complicated.ComplicatedMessage.MessagesEntry.key', index=0,
            number=1, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='value', full_name='complicated.ComplicatedMessage.MessagesEntry.value', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=b'8\001',
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=235,
    serialized_end=304,
)

_COMPLICATEDMESSAGE = _descriptor.Descriptor(
    name='ComplicatedMessage',
    full_name='complicated.ComplicatedMessage',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='message', full_name='complicated.ComplicatedMessage.message', index=0,
            number=1, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='uints', full_name='complicated.ComplicatedMessage.uints', index=1,
            number=2, type=13, cpp_type=3, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=b'\020\001', file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='messages', full_name='complicated.ComplicatedMessage.messages', index=2,
            number=3, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='count', full_name='complicated.ComplicatedMessage.count', index=3,
            number=4, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[_COMPLICATEDMESSAGE_MESSAGESENTRY, ],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=75,
    serialized_end=304,
)

_COMPLICATEDMESSAGE_MESSAGESENTRY.fields_by_name['value'].message_type = _MESSAGE
_COMPLICATEDMESSAGE_MESSAGESENTRY.containing_type = _COMPLICATEDMESSAGE
_COMPLICATEDMESSAGE.fields_by_name['message'].message_type = _MESSAGE
_COMPLICATEDMESSAGE.fields_by_name['messages'].message_type = _COMPLICATEDMESSAGE_MESSAGESENTRY
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['ComplicatedMessage'] = _COMPLICATEDMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
    'DESCRIPTOR': _MESSAGE,
    '__module__': 'examples.complicated.pb_pb2'
    # @@protoc_insertion_point(class_scope:complicated.Message)
})
_sym_db.RegisterMessage(Message)

ComplicatedMessage = _reflection.GeneratedProtocolMessageType('ComplicatedMessage', (_message.Message,), {

    'MessagesEntry': _reflection.GeneratedProtocolMessageType('MessagesEntry', (_message.Message,), {
        'DESCRIPTOR': _COMPLICATEDMESSAGE_MESSAGESENTRY,
        '__module__': 'examples.complicated.pb_pb2'
        # @@protoc_insertion_point(class_scope:complicated.ComplicatedMessage.MessagesEntry)
    }),
    'DESCRIPTOR': _COMPLICATEDMESSAGE,
    '__module__': 'examples.complicated.pb_pb2'
    # @@protoc_insertion_point(class_scope:complicated.ComplicatedMessage)
})
_sym_db.RegisterMessage(ComplicatedMessage)
_sym_db.RegisterMessage(ComplicatedMessage.MessagesEntry)


DESCRIPTOR._options = None
_COMPLICATEDMESSAGE_MESSAGESENTRY._options = None
_COMPLICATEDMESSAGE.fields_by_name['uints']._options = None

_SERVICE = _descriptor.ServiceDescriptor(
    name='Service',
    full_name='complicated.Service',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=306,
    serialized_end=389,
    methods=[
        _descriptor.MethodDescriptor(
            name='Test',
            full_name='complicated.Service.Test',
            index=0,
            containing_service=None,
            input_type=_COMPLICATEDMESSAGE,
            output_type=_COMPLICATEDMESSAGE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_SERVICE)

DESCRIPTOR.services_by_name['Service'] = _SERVICE

Service = service_reflection.GeneratedServiceType('Service', (_service.Service,), dict(
    DESCRIPTOR=_SERVICE,
    __module__='examples.complicated.pb_pb2'
))

Service_Stub = service_reflection.GeneratedServiceStubType('Service_Stub', (Service,), dict(
    DESCRIPTOR=_SERVICE,
    __module__='examples.complicated.pb_pb2'
))


# @@protoc_insertion_point(module_scope)
