# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pymaid/apps/monitor/monitor.proto

import sys
_b = sys.version_info[0] < 3 and (
    lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pymaid.pb import pymaid_pb2 as pymaid_dot_pb_dot_pymaid__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name='pymaid/apps/monitor/monitor.proto',
    package='pymaid.apps.monitor',
    syntax='proto3',
    serialized_pb=_b('\n!pymaid/apps/monitor/monitor.proto\x12\x13pymaid.apps.monitor\x1a\x16pymaid/pb/pymaid.proto\"\x0f\n\rHeartbeatResp2X\n\x0eMonitorService\x12\x46\n\x0fNotifyHeartbeat\x12\x0f.pymaid.pb.Void\x1a\".pymaid.apps.monitor.HeartbeatRespB\x03\x90\x01\x01\x62\x06proto3'),
    dependencies=[pymaid_dot_pb_dot_pymaid__pb2.DESCRIPTOR, ])


_HEARTBEATRESP = _descriptor.Descriptor(
    name='HeartbeatResp',
    full_name='pymaid.apps.monitor.HeartbeatResp',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=82,
    serialized_end=97,
)

DESCRIPTOR.message_types_by_name['HeartbeatResp'] = _HEARTBEATRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeartbeatResp = _reflection.GeneratedProtocolMessageType('HeartbeatResp', (_message.Message,), dict(
    DESCRIPTOR=_HEARTBEATRESP,
    __module__='pymaid.apps.monitor.monitor_pb2'
    # @@protoc_insertion_point(class_scope:pymaid.apps.monitor.HeartbeatResp)
))
_sym_db.RegisterMessage(HeartbeatResp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(
    descriptor_pb2.FileOptions(), _b('\220\001\001'))

_MONITORSERVICE = _descriptor.ServiceDescriptor(
    name='MonitorService',
    full_name='pymaid.apps.monitor.MonitorService',
    file=DESCRIPTOR,
    index=0,
    options=None,
    serialized_start=99,
    serialized_end=187,
    methods=[
        _descriptor.MethodDescriptor(
            name='NotifyHeartbeat',
            full_name='pymaid.apps.monitor.MonitorService.NotifyHeartbeat',
            index=0,
            containing_service=None,
            input_type=pymaid_dot_pb_dot_pymaid__pb2._VOID,
            output_type=_HEARTBEATRESP,
            options=None,
        ),
    ])

MonitorService = service_reflection.GeneratedServiceType('MonitorService', (_service.Service,), dict(
    DESCRIPTOR=_MONITORSERVICE,
    __module__='pymaid.apps.monitor.monitor_pb2'
))

MonitorService_Stub = service_reflection.GeneratedServiceStubType('MonitorService_Stub', (MonitorService,), dict(
    DESCRIPTOR=_MONITORSERVICE,
    __module__='pymaid.apps.monitor.monitor_pb2'
))


# @@protoc_insertion_point(module_scope)
