# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pymaid/apps/monitor/monitor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pymaid.pb.pymaid_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pymaid/apps/monitor/monitor.proto',
  package='pymaid.apps.monitor',
  serialized_pb=_b('\n!pymaid/apps/monitor/monitor.proto\x12\x13pymaid.apps.monitor\x1a\x16pymaid/pb/pymaid.proto\"C\n\rHeartbeatInfo\x12\x16\n\x0eneed_heartbeat\x18\x01 \x02(\x08\x12\x1a\n\x12heartbeat_interval\x18\x02 \x01(\x02\x32\x91\x01\n\x0eMonitorService\x12\x34\n\x10notify_heartbeat\x12\x0f.pymaid.pb.Void\x1a\x0f.pymaid.pb.Void\x12I\n\x12get_heartbeat_info\x12\x0f.pymaid.pb.Void\x1a\".pymaid.apps.monitor.HeartbeatInfoB\x03\x90\x01\x01')
  ,
  dependencies=[pymaid.pb.pymaid_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HEARTBEATINFO = _descriptor.Descriptor(
  name='HeartbeatInfo',
  full_name='pymaid.apps.monitor.HeartbeatInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='need_heartbeat', full_name='pymaid.apps.monitor.HeartbeatInfo.need_heartbeat', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heartbeat_interval', full_name='pymaid.apps.monitor.HeartbeatInfo.heartbeat_interval', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['HeartbeatInfo'] = _HEARTBEATINFO

HeartbeatInfo = _reflection.GeneratedProtocolMessageType('HeartbeatInfo', (_message.Message,), dict(
  DESCRIPTOR = _HEARTBEATINFO,
  __module__ = 'pymaid.apps.monitor.monitor_pb2'
  # @@protoc_insertion_point(class_scope:pymaid.apps.monitor.HeartbeatInfo)
  ))
_sym_db.RegisterMessage(HeartbeatInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\220\001\001'))

_MONITORSERVICE = _descriptor.ServiceDescriptor(
  name='MonitorService',
  full_name='pymaid.apps.monitor.MonitorService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=152,
  serialized_end=297,
  methods=[
  _descriptor.MethodDescriptor(
    name='notify_heartbeat',
    full_name='pymaid.apps.monitor.MonitorService.notify_heartbeat',
    index=0,
    containing_service=None,
    input_type=pymaid.pb.pymaid_pb2._VOID,
    output_type=pymaid.pb.pymaid_pb2._VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_heartbeat_info',
    full_name='pymaid.apps.monitor.MonitorService.get_heartbeat_info',
    index=1,
    containing_service=None,
    input_type=pymaid.pb.pymaid_pb2._VOID,
    output_type=_HEARTBEATINFO,
    options=None,
  ),
])

MonitorService = service_reflection.GeneratedServiceType('MonitorService', (_service.Service,), dict(
  DESCRIPTOR = _MONITORSERVICE,
  __module__ = 'pymaid.apps.monitor.monitor_pb2'
  ))

MonitorService_Stub = service_reflection.GeneratedServiceStubType('MonitorService_Stub', (MonitorService,), dict(
  DESCRIPTOR = _MONITORSERVICE,
  __module__ = 'pymaid.apps.monitor.monitor_pb2'
  ))


# @@protoc_insertion_point(module_scope)
