# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: examples/heartbeat/heartbeat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pymaid.pb import pymaid_pb2 as pymaid_dot_pb_dot_pymaid__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='examples/heartbeat/heartbeat.proto',
  package='heartbeat',
  serialized_pb=_b('\n\"examples/heartbeat/heartbeat.proto\x12\theartbeat\x1a\x16pymaid/pb/pymaid.proto\"\n\n\x08Response2G\n\x0bLongPlaying\x12\x38\n\x10over_two_seconds\x12\x0f.pymaid.pb.Void\x1a\x13.heartbeat.ResponseB\x03\x90\x01\x01\x62\x06proto3')
  ,
  dependencies=[pymaid_dot_pb_dot_pymaid__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='heartbeat.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'examples.heartbeat.heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:heartbeat.Response)
  ))
_sym_db.RegisterMessage(Response)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\220\001\001'))

_LONGPLAYING = _descriptor.ServiceDescriptor(
  name='LongPlaying',
  full_name='heartbeat.LongPlaying',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=85,
  serialized_end=156,
  methods=[
  _descriptor.MethodDescriptor(
    name='over_two_seconds',
    full_name='heartbeat.LongPlaying.over_two_seconds',
    index=0,
    containing_service=None,
    input_type=pymaid_dot_pb_dot_pymaid__pb2._VOID,
    output_type=_RESPONSE,
    options=None,
  ),
])

LongPlaying = service_reflection.GeneratedServiceType('LongPlaying', (_service.Service,), dict(
  DESCRIPTOR = _LONGPLAYING,
  __module__ = 'examples.heartbeat.heartbeat_pb2'
  ))

LongPlaying_Stub = service_reflection.GeneratedServiceStubType('LongPlaying_Stub', (LongPlaying,), dict(
  DESCRIPTOR = _LONGPLAYING,
  __module__ = 'examples.heartbeat.heartbeat_pb2'
  ))


# @@protoc_insertion_point(module_scope)
