# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pymaid/rpc/pymaid.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='pymaid/rpc/pymaid.proto',
    package='pymaid.rpc',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=b'\n\x17pymaid/rpc/pymaid.proto\x12\npymaid.rpc\"\xc5\x03\n\nController\x12\x17\n\x0ftransmission_id\x18\x01 \x01(\r\x12\x36\n\x0bpacket_type\x18\x02 \x01(\x0e\x32!.pymaid.rpc.Controller.PacketType\x12\x37\n\x0cpacket_flags\x18\x03 \x01(\x0e\x32!.pymaid.rpc.Controller.PacketFlag\x12\x31\n\x08priority\x18\x04 \x01(\x0e\x32\x1f.pymaid.rpc.Controller.Priority\x12\x16\n\x0eservice_method\x18\x05 \x01(\t\x12\x14\n\x0cis_cancelled\x18\x06 \x01(\x08\x12\x11\n\tis_failed\x18\x07 \x01(\x08\x12\x14\n\x0cpayload_size\x18\x08 \x01(\r\"4\n\nPacketType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07REQUEST\x10\x01\x12\x0c\n\x08RESPONSE\x10\x02\"E\n\nPacketFlag\x12\x08\n\x04NULL\x10\x00\x12\n\n\x06STREAM\x10\x01\x12\x0e\n\nEND_STREAM\x10\x02\x12\x11\n\rCANCEL_STREAM\x10\x03\"&\n\x08Priority\x12\x07\n\x03LOW\x10\x00\x12\x07\n\x03MID\x10\x01\x12\x08\n\x04HIGH\x10\x02\"\x08\n\x06RpcAck\"\x06\n\x04Void\";\n\x0c\x45rrorMessage\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\tb\x06proto3'
)


_CONTROLLER_PACKETTYPE = _descriptor.EnumDescriptor(
    name='PacketType',
    full_name='pymaid.rpc.Controller.PacketType',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='UNKNOWN', index=0, number=0,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='REQUEST', index=1, number=1,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='RESPONSE', index=2, number=2,
            serialized_options=None,
            type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=330,
    serialized_end=382,
)
_sym_db.RegisterEnumDescriptor(_CONTROLLER_PACKETTYPE)

_CONTROLLER_PACKETFLAG = _descriptor.EnumDescriptor(
    name='PacketFlag',
    full_name='pymaid.rpc.Controller.PacketFlag',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='NULL', index=0, number=0,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='STREAM', index=1, number=1,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='END_STREAM', index=2, number=2,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='CANCEL_STREAM', index=3, number=3,
            serialized_options=None,
            type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=384,
    serialized_end=453,
)
_sym_db.RegisterEnumDescriptor(_CONTROLLER_PACKETFLAG)

_CONTROLLER_PRIORITY = _descriptor.EnumDescriptor(
    name='Priority',
    full_name='pymaid.rpc.Controller.Priority',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='LOW', index=0, number=0,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='MID', index=1, number=1,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='HIGH', index=2, number=2,
            serialized_options=None,
            type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=455,
    serialized_end=493,
)
_sym_db.RegisterEnumDescriptor(_CONTROLLER_PRIORITY)


_CONTROLLER = _descriptor.Descriptor(
    name='Controller',
    full_name='pymaid.rpc.Controller',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='transmission_id', full_name='pymaid.rpc.Controller.transmission_id', index=0,
            number=1, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='packet_type', full_name='pymaid.rpc.Controller.packet_type', index=1,
            number=2, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='packet_flags', full_name='pymaid.rpc.Controller.packet_flags', index=2,
            number=3, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='priority', full_name='pymaid.rpc.Controller.priority', index=3,
            number=4, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='service_method', full_name='pymaid.rpc.Controller.service_method', index=4,
            number=5, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='is_cancelled', full_name='pymaid.rpc.Controller.is_cancelled', index=5,
            number=6, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='is_failed', full_name='pymaid.rpc.Controller.is_failed', index=6,
            number=7, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='payload_size', full_name='pymaid.rpc.Controller.payload_size', index=7,
            number=8, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
        _CONTROLLER_PACKETTYPE,
        _CONTROLLER_PACKETFLAG,
        _CONTROLLER_PRIORITY,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=40,
    serialized_end=493,
)


_RPCACK = _descriptor.Descriptor(
    name='RpcAck',
    full_name='pymaid.rpc.RpcAck',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=495,
    serialized_end=503,
)


_VOID = _descriptor.Descriptor(
    name='Void',
    full_name='pymaid.rpc.Void',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=505,
    serialized_end=511,
)


_ERRORMESSAGE = _descriptor.Descriptor(
    name='ErrorMessage',
    full_name='pymaid.rpc.ErrorMessage',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='code', full_name='pymaid.rpc.ErrorMessage.code', index=0,
            number=1, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='message', full_name='pymaid.rpc.ErrorMessage.message', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='data', full_name='pymaid.rpc.ErrorMessage.data', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=513,
    serialized_end=572,
)

_CONTROLLER.fields_by_name['packet_type'].enum_type = _CONTROLLER_PACKETTYPE
_CONTROLLER.fields_by_name['packet_flags'].enum_type = _CONTROLLER_PACKETFLAG
_CONTROLLER.fields_by_name['priority'].enum_type = _CONTROLLER_PRIORITY
_CONTROLLER_PACKETTYPE.containing_type = _CONTROLLER
_CONTROLLER_PACKETFLAG.containing_type = _CONTROLLER
_CONTROLLER_PRIORITY.containing_type = _CONTROLLER
DESCRIPTOR.message_types_by_name['Controller'] = _CONTROLLER
DESCRIPTOR.message_types_by_name['RpcAck'] = _RPCACK
DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['ErrorMessage'] = _ERRORMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Controller = _reflection.GeneratedProtocolMessageType('Controller', (_message.Message,), {
    'DESCRIPTOR': _CONTROLLER,
    '__module__': 'pymaid.rpc.pymaid_pb2'
    # @@protoc_insertion_point(class_scope:pymaid.rpc.Controller)
})
_sym_db.RegisterMessage(Controller)

RpcAck = _reflection.GeneratedProtocolMessageType('RpcAck', (_message.Message,), {
    'DESCRIPTOR': _RPCACK,
    '__module__': 'pymaid.rpc.pymaid_pb2'
    # @@protoc_insertion_point(class_scope:pymaid.rpc.RpcAck)
})
_sym_db.RegisterMessage(RpcAck)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
    'DESCRIPTOR': _VOID,
    '__module__': 'pymaid.rpc.pymaid_pb2'
    # @@protoc_insertion_point(class_scope:pymaid.rpc.Void)
})
_sym_db.RegisterMessage(Void)

ErrorMessage = _reflection.GeneratedProtocolMessageType('ErrorMessage', (_message.Message,), {
    'DESCRIPTOR': _ERRORMESSAGE,
    '__module__': 'pymaid.rpc.pymaid_pb2'
    # @@protoc_insertion_point(class_scope:pymaid.rpc.ErrorMessage)
})
_sym_db.RegisterMessage(ErrorMessage)


# @@protoc_insertion_point(module_scope)
