goog.provide("proto.pymaid.pb.Controller");goog.provide("proto.pymaid.pb.Controller.PacketType");goog.provide("proto.pymaid.pb.ErrorMessage");goog.provide("proto.pymaid.pb.RpcAck");goog.provide("proto.pymaid.pb.Void");goog.require("jspb.BinaryReader");goog.require("jspb.BinaryWriter");goog.require("jspb.Message");proto.pymaid.pb.Controller=function(opt_data){jspb.Message.initialize(this,opt_data,0,-1,null,null)};goog.inherits(proto.pymaid.pb.Controller,jspb.Message);
if(goog.DEBUG&&!COMPILED)proto.pymaid.pb.Controller.displayName="proto.pymaid.pb.Controller";
if(jspb.Message.GENERATE_TO_OBJECT){proto.pymaid.pb.Controller.prototype.toObject=function(opt_includeInstance){return proto.pymaid.pb.Controller.toObject(opt_includeInstance,this)};proto.pymaid.pb.Controller.toObject=function(includeInstance,msg){var f,obj={serviceMethod:jspb.Message.getFieldWithDefault(msg,1,""),packetType:jspb.Message.getFieldWithDefault(msg,2,0),transmissionId:jspb.Message.getFieldWithDefault(msg,3,0),isCanceled:jspb.Message.getFieldWithDefault(msg,4,false),isFailed:jspb.Message.getFieldWithDefault(msg,
5,false)};if(includeInstance)obj.$jspbMessageInstance=msg;return obj}}
if(jspb.Message.GENERATE_FROM_OBJECT)proto.pymaid.pb.Controller.fromObject=function(obj){var f,msg=new proto.pymaid.pb.Controller;goog.isDef(obj.serviceMethod)&&jspb.Message.setField(msg,1,obj.serviceMethod);goog.isDef(obj.packetType)&&jspb.Message.setField(msg,2,obj.packetType);goog.isDef(obj.transmissionId)&&jspb.Message.setField(msg,3,obj.transmissionId);goog.isDef(obj.isCanceled)&&jspb.Message.setField(msg,4,obj.isCanceled);goog.isDef(obj.isFailed)&&jspb.Message.setField(msg,5,obj.isFailed);return msg};
proto.pymaid.pb.Controller.deserializeBinary=function(bytes){var reader=new jspb.BinaryReader(bytes);var msg=new proto.pymaid.pb.Controller;return proto.pymaid.pb.Controller.deserializeBinaryFromReader(msg,reader)};
proto.pymaid.pb.Controller.deserializeBinaryFromReader=function(msg,reader){while(reader.nextField()){if(reader.isEndGroup())break;var field=reader.getFieldNumber();switch(field){case 1:var value=reader.readString();msg.setServiceMethod(value);break;case 2:var value=reader.readEnum();msg.setPacketType(value);break;case 3:var value=reader.readUint32();msg.setTransmissionId(value);break;case 4:var value=reader.readBool();msg.setIsCanceled(value);break;case 5:var value=reader.readBool();msg.setIsFailed(value);
break;default:reader.skipField();break}}return msg};proto.pymaid.pb.Controller.prototype.serializeBinary=function(){var writer=new jspb.BinaryWriter;proto.pymaid.pb.Controller.serializeBinaryToWriter(this,writer);return writer.getResultBuffer()};
proto.pymaid.pb.Controller.serializeBinaryToWriter=function(message,writer){var f=undefined;f=message.getServiceMethod();if(f.length>0)writer.writeString(1,f);f=message.getPacketType();if(f!==0)writer.writeEnum(2,f);f=message.getTransmissionId();if(f!==0)writer.writeUint32(3,f);f=message.getIsCanceled();if(f)writer.writeBool(4,f);f=message.getIsFailed();if(f)writer.writeBool(5,f)};proto.pymaid.pb.Controller.PacketType={UNKNOWN:0,REQUEST:1,RESPONSE:2,NOTIFICATION:3};
proto.pymaid.pb.Controller.prototype.getServiceMethod=function(){return jspb.Message.getFieldWithDefault(this,1,"")};proto.pymaid.pb.Controller.prototype.setServiceMethod=function(value){jspb.Message.setProto3StringField(this,1,value)};proto.pymaid.pb.Controller.prototype.getPacketType=function(){return jspb.Message.getFieldWithDefault(this,2,0)};proto.pymaid.pb.Controller.prototype.setPacketType=function(value){jspb.Message.setProto3EnumField(this,2,value)};
proto.pymaid.pb.Controller.prototype.getTransmissionId=function(){return jspb.Message.getFieldWithDefault(this,3,0)};proto.pymaid.pb.Controller.prototype.setTransmissionId=function(value){jspb.Message.setProto3IntField(this,3,value)};proto.pymaid.pb.Controller.prototype.getIsCanceled=function(){return jspb.Message.getFieldWithDefault(this,4,false)};proto.pymaid.pb.Controller.prototype.setIsCanceled=function(value){jspb.Message.setProto3BooleanField(this,4,value)};
proto.pymaid.pb.Controller.prototype.getIsFailed=function(){return jspb.Message.getFieldWithDefault(this,5,false)};proto.pymaid.pb.Controller.prototype.setIsFailed=function(value){jspb.Message.setProto3BooleanField(this,5,value)};proto.pymaid.pb.RpcAck=function(opt_data){jspb.Message.initialize(this,opt_data,0,-1,null,null)};goog.inherits(proto.pymaid.pb.RpcAck,jspb.Message);if(goog.DEBUG&&!COMPILED)proto.pymaid.pb.RpcAck.displayName="proto.pymaid.pb.RpcAck";
if(jspb.Message.GENERATE_TO_OBJECT){proto.pymaid.pb.RpcAck.prototype.toObject=function(opt_includeInstance){return proto.pymaid.pb.RpcAck.toObject(opt_includeInstance,this)};proto.pymaid.pb.RpcAck.toObject=function(includeInstance,msg){var f,obj={};if(includeInstance)obj.$jspbMessageInstance=msg;return obj}}if(jspb.Message.GENERATE_FROM_OBJECT)proto.pymaid.pb.RpcAck.fromObject=function(obj){var f,msg=new proto.pymaid.pb.RpcAck;return msg};
proto.pymaid.pb.RpcAck.deserializeBinary=function(bytes){var reader=new jspb.BinaryReader(bytes);var msg=new proto.pymaid.pb.RpcAck;return proto.pymaid.pb.RpcAck.deserializeBinaryFromReader(msg,reader)};proto.pymaid.pb.RpcAck.deserializeBinaryFromReader=function(msg,reader){while(reader.nextField()){if(reader.isEndGroup())break;var field=reader.getFieldNumber();switch(field){default:reader.skipField();break}}return msg};
proto.pymaid.pb.RpcAck.prototype.serializeBinary=function(){var writer=new jspb.BinaryWriter;proto.pymaid.pb.RpcAck.serializeBinaryToWriter(this,writer);return writer.getResultBuffer()};proto.pymaid.pb.RpcAck.serializeBinaryToWriter=function(message,writer){var f=undefined};proto.pymaid.pb.Void=function(opt_data){jspb.Message.initialize(this,opt_data,0,-1,null,null)};goog.inherits(proto.pymaid.pb.Void,jspb.Message);if(goog.DEBUG&&!COMPILED)proto.pymaid.pb.Void.displayName="proto.pymaid.pb.Void";
if(jspb.Message.GENERATE_TO_OBJECT){proto.pymaid.pb.Void.prototype.toObject=function(opt_includeInstance){return proto.pymaid.pb.Void.toObject(opt_includeInstance,this)};proto.pymaid.pb.Void.toObject=function(includeInstance,msg){var f,obj={};if(includeInstance)obj.$jspbMessageInstance=msg;return obj}}if(jspb.Message.GENERATE_FROM_OBJECT)proto.pymaid.pb.Void.fromObject=function(obj){var f,msg=new proto.pymaid.pb.Void;return msg};
proto.pymaid.pb.Void.deserializeBinary=function(bytes){var reader=new jspb.BinaryReader(bytes);var msg=new proto.pymaid.pb.Void;return proto.pymaid.pb.Void.deserializeBinaryFromReader(msg,reader)};proto.pymaid.pb.Void.deserializeBinaryFromReader=function(msg,reader){while(reader.nextField()){if(reader.isEndGroup())break;var field=reader.getFieldNumber();switch(field){default:reader.skipField();break}}return msg};
proto.pymaid.pb.Void.prototype.serializeBinary=function(){var writer=new jspb.BinaryWriter;proto.pymaid.pb.Void.serializeBinaryToWriter(this,writer);return writer.getResultBuffer()};proto.pymaid.pb.Void.serializeBinaryToWriter=function(message,writer){var f=undefined};proto.pymaid.pb.ErrorMessage=function(opt_data){jspb.Message.initialize(this,opt_data,0,-1,null,null)};goog.inherits(proto.pymaid.pb.ErrorMessage,jspb.Message);if(goog.DEBUG&&!COMPILED)proto.pymaid.pb.ErrorMessage.displayName="proto.pymaid.pb.ErrorMessage";
if(jspb.Message.GENERATE_TO_OBJECT){proto.pymaid.pb.ErrorMessage.prototype.toObject=function(opt_includeInstance){return proto.pymaid.pb.ErrorMessage.toObject(opt_includeInstance,this)};proto.pymaid.pb.ErrorMessage.toObject=function(includeInstance,msg){var f,obj={code:jspb.Message.getFieldWithDefault(msg,1,0),message:jspb.Message.getFieldWithDefault(msg,2,""),data:jspb.Message.getFieldWithDefault(msg,3,"")};if(includeInstance)obj.$jspbMessageInstance=msg;return obj}}
if(jspb.Message.GENERATE_FROM_OBJECT)proto.pymaid.pb.ErrorMessage.fromObject=function(obj){var f,msg=new proto.pymaid.pb.ErrorMessage;goog.isDef(obj.code)&&jspb.Message.setField(msg,1,obj.code);goog.isDef(obj.message)&&jspb.Message.setField(msg,2,obj.message);goog.isDef(obj.data)&&jspb.Message.setField(msg,3,obj.data);return msg};
proto.pymaid.pb.ErrorMessage.deserializeBinary=function(bytes){var reader=new jspb.BinaryReader(bytes);var msg=new proto.pymaid.pb.ErrorMessage;return proto.pymaid.pb.ErrorMessage.deserializeBinaryFromReader(msg,reader)};
proto.pymaid.pb.ErrorMessage.deserializeBinaryFromReader=function(msg,reader){while(reader.nextField()){if(reader.isEndGroup())break;var field=reader.getFieldNumber();switch(field){case 1:var value=reader.readUint32();msg.setCode(value);break;case 2:var value=reader.readString();msg.setMessage(value);break;case 3:var value=reader.readString();msg.setData(value);break;default:reader.skipField();break}}return msg};
proto.pymaid.pb.ErrorMessage.prototype.serializeBinary=function(){var writer=new jspb.BinaryWriter;proto.pymaid.pb.ErrorMessage.serializeBinaryToWriter(this,writer);return writer.getResultBuffer()};proto.pymaid.pb.ErrorMessage.serializeBinaryToWriter=function(message,writer){var f=undefined;f=message.getCode();if(f!==0)writer.writeUint32(1,f);f=message.getMessage();if(f.length>0)writer.writeString(2,f);f=message.getData();if(f.length>0)writer.writeString(3,f)};
proto.pymaid.pb.ErrorMessage.prototype.getCode=function(){return jspb.Message.getFieldWithDefault(this,1,0)};proto.pymaid.pb.ErrorMessage.prototype.setCode=function(value){jspb.Message.setProto3IntField(this,1,value)};proto.pymaid.pb.ErrorMessage.prototype.getMessage=function(){return jspb.Message.getFieldWithDefault(this,2,"")};proto.pymaid.pb.ErrorMessage.prototype.setMessage=function(value){jspb.Message.setProto3StringField(this,2,value)};
proto.pymaid.pb.ErrorMessage.prototype.getData=function(){return jspb.Message.getFieldWithDefault(this,3,"")};proto.pymaid.pb.ErrorMessage.prototype.setData=function(value){jspb.Message.setProto3StringField(this,3,value)};